---
title: "Generate files for groups"
---

```{r, include=FALSE, message=FALSE, results='hide', warning=FALSE, error=FALSE}
library(readxl)
library(tidyverse)
# requires Java
library("xlsx")
```

```{r}
path_input <- "../input"
path_output <- "../output"
```


Prepare the template
```{r}
template_df <- read_excel(file.path(path_input, "template.xlsx"))
last_template_row <- which(template_df[1] == "My name (x)")


```

Process student data to generate templates
```{r}
groups_data <- read_excel(file.path(path_input, "students_groups.xlsx"))
data_list <- split(groups_data, f = groups_data$Team) 

for (i in 1:last(groups_data$Team)) {

  # add columns
  individual_df <- 
    data_list[[i]] %>% 
    mutate(
      `My name (x)` = NA,
      `Rating` = NA,
      `Comments` = NA) %>% 
    select(
      `My name (x)`,
      `Person`,
      `Rating`,
      `Comments`,
      `Team`)
  
  # load the template (NOTE: we need to re-load the template for every team,
  # otherwise extraneous rows of the preceding teams will present when a 
  # subsequent team has fewer members)
  wb <- loadWorkbook(file.path(path_input, "template.xlsx"))
  sheet <- getSheets(wb)[[1]]
  
  
  # NOTE: colors don't work properly see ?CellStyle
  # styleGreen <- CellStyle(wb) + Fill(backgroundColor = "#E2EFDA")
  # styleOrange <- CellStyle(wb) + Fill(backgroundColor = "#FFE699")
  
  # append the team-specific information
  addDataFrame(as.data.frame(individual_df), 
               sheet, 
               startRow = last_template_row + 2,
               col.names = TRUE,
               row.names = FALSE)
               # colStyle = list(
               #   `1` = styleGreen,
               #   `3` = styleGreen,
               #   `4` = styleOrange))
  
  # write output file
  file_name <- file.path(path_output, 
                         "template_for_students", 
                         sprintf("Peer assessment Team %02d.xlsx", i))
  saveWorkbook(wb, file_name)
}
```





