---
title: "Calculate the grading adjustment factor accordinng to WebPA"
---

```{r, include=FALSE, message=FALSE, results='hide', warning=FALSE, error=FALSE}
library(tidyverse)
library(readxl)
library(xlsx)

source("R/calculate_rating.R")
options("dplyr.summarise.inform" = FALSE)  # disables warning in dplyr::summary() (experimental lifecycle)

```
```{r}
path_input <- "../input"
path_output <- file.path("../output", "calculated_adjustments.xlsx")
```

Read the sizes of the groups from sizes.csv.  
Set path to submissions folder with the following structure:  
- submissions/  
  - group_01/  
    - file1.xlsx  (NOTE: the file name doesn't matter)
    - file2.xlsx
    ...
  - group_02/  
    - file1.xlsx
    - file2.xlsx

```{r}
sizes_df <- 
  read_excel(file.path(path_input, "students_groups.xlsx")) %>% 
  group_by(Team) %>% 
  summarize(group_size = n()) %>% 
  ungroup() %>% 
  select(group_number = Team, group_size)

```

A function to extract ratings from submitted Excel files:
```{r}
extract_rating <- function(individual_path) {
  a_rating_df <- 
    read_excel(individual_path, skip = 10) %>% # TODO: 10 is hard-coded. Better determine it from the template
    select(
      `x` = "My name (x)",
      `name` = "Person",
      `rating` = "Rating",
      `comment` = "Comments",
      `group` = "Team")
  
  a_rating_df %>% 
    mutate(own_name = a_rating_df$name[which(a_rating_df$x == "x")]) %>% 
    select(-comment, -x)
}
```


```{r}
# TODO: iteration based on submitted file will generate the adjustment only for submitted groups
path_ratings  <-  file.path(path_input, "submitted_ratings")

submitted_paths <- list.files(path_ratings, pattern = '*.xlsx', 
                              full.names = TRUE, recursive = TRUE)
number_of_submissions = length(submitted_paths)

rating_df <- 
  map_dfr(submitted_paths, extract_rating)
for (path in groups_paths) {
  results <- rbind(results, calculate_rating(path, i, sizes_df$group_size[sizes_df$group_number==i]))
}

# saves excel file with the results
write.xlsx(as.data.frame(results), path_output, col.names = TRUE, showNA = FALSE, row.names = FALSE)
```

To view results here:
```{r}
results
```







